### ISSUE TITLE
Use custom Docker images

### ISSUE THREAD

**Issue by ataylorme** [felixarntz/wordpressdev#1]
Rather than installing global packages as part of services that are run after the containers are initialized the global packages should be instead be defined in a custom to a Dockerfile.

See https://docs.devwithlando.io/config/advanced.html#using-dockerfiles

**Comment by felixarntz** [comment]
I think that makes sense to me. Could you (as time permits) spin up a simple PR just to give a better idea of what that could look like for this project?

**Comment by westonruter** [comment]
Why is a `Dockerfile` better than just including the gulp installation as part of a `install_dependencies_as_me_internal` under the `node` service? Seems better to maintain that way.

**Comment by westonruter** [comment]
For example I can see on https://docs.devwithlando.io/services/node.html that Gulp can be installed via the `.lando.yml` as follows:

```yml
# Spin up services to run a basic node server
services:

  # Create a node instance
  appserver:
    #...

    # Optionally install the following npm dependencies globally
    # These follow the normal package.json form
    #
    # Note that most deps should be installed by the normal npm install, this is
    # for things like gulp/grunt cli that are global dependencies
    globals:
      gulp-cli: "latest"
```
