### ISSUE TITLE
Address loopback request problem

### ISSUE THREAD

**Issue by westonruter** [felixarntz/wordpressdev#3]
We need to add the `lndo.site` URL to the hosts file in the containers to fix loopback requests, apparently. Perhaps here:

https://github.com/felixarntz/wordpressdev/blob/b6a746c7a9bbcacbfff627bff6f592aca6d3e88e/.lando.yml#L16-L21

**Comment by westonruter** [comment]
@ataylorme Are you aware if something like this will work:

```yml
services:
  appserver:
    install_dependencies_as_root:
      # Allow loopback requests to work.
      - echo "127.0.0.1  wordpressdev.lando.dev" >> /etc/hosts
```

Have you also encountered the loopback request problem?

**Comment by westonruter** [comment]
Just saw this on the docs:

![image](https://user-images.githubusercontent.com/134745/50364861-bc721500-0526-11e9-9846-43af702bf720.png)

I can confirm this works:

```yml
services:
  appserver:
    run_as_root:
      # Allow loopback requests to work.
      - echo "127.0.0.1  wordpressdev.lando.site" >> /etc/hosts
```

Loopback requests work successfully with that change.
